:headline: wampum
:body: |
    *senior design 2015*

    This project is a network of wireless heart rate monitors to be used 
    in ad-hoc recovery rooms following disaster scenarios. The wireless monitors, or nodes, are 
    placed on patients and determine their heart rate using [photoplethysmography](https://en.wikipedia.org/wiki/Photoplethysmogram). 
    The data sent from each node is viewed on a nearby laptop where medical personnel 
    can monitor patients and be alerted of any abnormal activity.

    The project is dubbed WAMPUM for **W**ireless **A**ggregating **M**ultinode, **PU**lse **M**onitor.

    Created with [Jeremy Warner](http://jeremywrnr.com/project/wampum/), Jae Min Choi, and Ivy Racquel for senior design
    at the University of Rochester.
    
    [code](https://github.com/jeremywrnr/wampum)

:youtube:
  - 
    -uUUcI6ASRs