:headline: rgb backlight
:body: |
    *2010*

    A high powered, [RGB LED](http://www.sparkfun.com/products/8718) powered by a LED driver based on [dan's Instructable](http://www.instructables.com/id/Circuits-for-using-High-Power-LED-s/) and an Arduino microcontroller.

    The LED module connects to the controller through a USB connector and the controller is powered by a 5 volt power supply. After powering on the device, a push button on the top of the controller allows the user to cycle through a series of colors that are embedded in the code. Holding down the pushbutton at anytime puts the controller into an RGB cycle mode (moodlight mode).

    [code](https://gist.github.com/4522570)


:videos:
  -
    29803836