:headline: electric jetta
:body: |
    *2008-2011*

    Electric car conversion of a VW Jetta. Goes about 25 miles/charge with a top speed of 55mph. The car was dismantled in 2011 after having multiple mechanical issues.
    
    Major Features:
    
    [Curtis controller][1], [Warp 9 motor][2], [12 Trojan T-1275 (144v)][3], [Battery watering system][4], [PakTrakr battery monitor][5], [Quick Charge][6], [Power brakes][7]



    [1]: http://www.evsource.com/tls_curtis.php
    [2]: http://www.evsource.com/tls_warp9.php
    [3]: http://www.trojanbattery.com/Products/T-127512V.aspx
    [4]: http://www.trojanbattery.com/Products/HydroLink.aspx
    [5]: http://www.zapworld.com/node/899
    [6]: http://quickcharge.com/Select-a-charge%20ON%20BOARD.htm
    [7]: http://www.evsource.com/tls_braking_system.php