:headline: spinning graduation cap
:body: |
    *2011*

    A motor recycled from an old CD drive was placed inside the cap and the spindle was glued to the top square. The motor is powered by 1 AA and a small tact switch is pressed to activate spin power.



:videos:
  - 
    25466719