:headline: portable cable tv
:body: |
    *2008*

    Using the [RF Link video transmission system](http://www.rflinkusa.com/products_AVS5811.html), a 5" screen, and a battery. This device allows you to watch cable television from any room in your home. Connect the transmitter to your cable box, put on the channel you want to watch and the video will stream to the device. 
