:headline: wireless data transmission
:body: |
    *2011*

    Installed on University of Rochester's [SAE Baja Team](http://www.me.rochester.edu/~baja/) for 2012 competition.

    The [Arudino Fio](http://www.sparkfun.com/products/10116) is used in this project to sample analog data signals and send them wirelessly using a pair of [Xbee modules](http://www.sparkfun.com/products/8742).
    All data is displayed on the dashboard using analog electronics and in realtime on a nearby computer that is running the display program.