:headline: power quality monitor
:body: |
    *summer 2013*

    This is a WiFi enabled three-phase power quality monitor. The device uses an Arudino MEGA as its brains, a [MAXQ3183](http://www.maximintegrated.com/datasheet/index.mvp/id/6353) power meter IC to read power quality data, and a [WiFly Shield](https://www.sparkfun.com/products/9954) for communication.
    Two devices are currently installed at the University of Rochester and collecting data which can be viewed [here](http://www.ece.rochester.edu/projects/power/).
    
    This project was funded by the Xerox Corporation and the STEP of the US Department of Energy. Preliminary work was done by David Fung and Jak Yung under [Professor Thomas Jones](http://www.ece.rochester.edu/~jones/).
