# The key value pairs found below are available within the templates.
# {{site_name}}, {{url}}, {{copyright}} and {{analytics_code}}

:site_name: Eddie Samuels
:url: http://eddiesamuels.com
:copyright: today
:analytics_code: UA-27913774-1